name: localization

description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.0.0
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  bloc_concurrency: ^0.2.0
  equatable: ^2.0.3
  stream_transform: ^2.0.0
  dio: ^4.0.4
  intl: ^0.17.0
  sizer: ^2.0.15
  get_it: ^7.2.0
  easy_localization: ^3.0.0
  path_provider: ^2.0.9
  easy_localization_loader: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.0
  mocktail: ^0.2.0
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:

    - assets/lang/ar-AR.json
    - assets/lang/en-US.json